// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MillionAndUp.Data;

namespace MillionAndUp.Data.Migrations
{
    [DbContext(typeof(MillionUpDbContext))]
    [Migration("20210425000135_AddUsersModel")]
    partial class AddUsersModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Address = "North",
                            Birthday = new DateTime(1994, 6, 2, 2, 48, 29, 846, DateTimeKind.Unspecified).AddTicks(2571),
                            Name = "Salvador Leffler",
                            Photo = "https://picsum.photos/640/480/?image=440"
                        },
                        new
                        {
                            OwnerId = 2,
                            Address = "North",
                            Birthday = new DateTime(2014, 2, 18, 1, 57, 40, 886, DateTimeKind.Unspecified).AddTicks(8313),
                            Name = "Araceli Wehner",
                            Photo = "https://picsum.photos/640/480/?image=642"
                        },
                        new
                        {
                            OwnerId = 3,
                            Address = "West",
                            Birthday = new DateTime(1997, 4, 6, 15, 33, 42, 267, DateTimeKind.Unspecified).AddTicks(3),
                            Name = "Jennifer Jerde",
                            Photo = "https://picsum.photos/640/480/?image=999"
                        },
                        new
                        {
                            OwnerId = 4,
                            Address = "East",
                            Birthday = new DateTime(2011, 4, 3, 11, 50, 48, 416, DateTimeKind.Unspecified).AddTicks(4642),
                            Name = "Pamela Osinski",
                            Photo = "https://picsum.photos/640/480/?image=191"
                        },
                        new
                        {
                            OwnerId = 5,
                            Address = "Northeast",
                            Birthday = new DateTime(2016, 6, 7, 22, 41, 26, 184, DateTimeKind.Unspecified).AddTicks(625),
                            Name = "Braden Zemlak",
                            Photo = "https://picsum.photos/640/480/?image=619"
                        },
                        new
                        {
                            OwnerId = 6,
                            Address = "West",
                            Birthday = new DateTime(2006, 8, 9, 23, 43, 58, 832, DateTimeKind.Unspecified).AddTicks(7930),
                            Name = "Donnell Carroll",
                            Photo = "https://picsum.photos/640/480/?image=256"
                        },
                        new
                        {
                            OwnerId = 7,
                            Address = "North",
                            Birthday = new DateTime(1995, 8, 10, 21, 21, 33, 117, DateTimeKind.Unspecified).AddTicks(2855),
                            Name = "Roy Bayer",
                            Photo = "https://picsum.photos/640/480/?image=807"
                        },
                        new
                        {
                            OwnerId = 8,
                            Address = "Southeast",
                            Birthday = new DateTime(2008, 8, 11, 19, 12, 50, 942, DateTimeKind.Unspecified).AddTicks(3126),
                            Name = "Aurore Oberbrunner",
                            Photo = "https://picsum.photos/640/480/?image=672"
                        },
                        new
                        {
                            OwnerId = 9,
                            Address = "North",
                            Birthday = new DateTime(2000, 5, 23, 5, 0, 33, 24, DateTimeKind.Unspecified).AddTicks(4541),
                            Name = "Theodore Schneider",
                            Photo = "https://picsum.photos/640/480/?image=311"
                        },
                        new
                        {
                            OwnerId = 10,
                            Address = "Northeast",
                            Birthday = new DateTime(2014, 4, 27, 1, 28, 45, 408, DateTimeKind.Unspecified).AddTicks(2960),
                            Name = "Madyson Bechtelar",
                            Photo = "https://picsum.photos/640/480/?image=909"
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "Southeast",
                            InternalCode = "THX",
                            Name = "Andrew Stanton",
                            OwnerId = 8,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "Southwest",
                            InternalCode = "SCSI",
                            Name = "Skylar Swaniawski",
                            OwnerId = 5,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "Southwest",
                            InternalCode = "SMS",
                            Name = "Tom Muller",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 4,
                            Address = "West",
                            InternalCode = "ADP",
                            Name = "Augustine Miller",
                            OwnerId = 7,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 5,
                            Address = "Northeast",
                            InternalCode = "SMS",
                            Name = "Marcelle Skiles",
                            OwnerId = 1,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 6,
                            Address = "South",
                            InternalCode = "PNG",
                            Name = "Brown Beatty",
                            OwnerId = 4,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 7,
                            Address = "Northwest",
                            InternalCode = "XML",
                            Name = "Harley Hamill",
                            OwnerId = 7,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 8,
                            Address = "East",
                            InternalCode = "SQL",
                            Name = "Rhiannon Labadie",
                            OwnerId = 7,
                            Price = 2017m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 9,
                            Address = "West",
                            InternalCode = "TCP",
                            Name = "Lilliana Gleason",
                            OwnerId = 2,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 10,
                            Address = "East",
                            InternalCode = "JBOD",
                            Name = "Celestino Bradtke",
                            OwnerId = 9,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 11,
                            Address = "Northwest",
                            InternalCode = "SSL",
                            Name = "Brook Runolfsson",
                            OwnerId = 7,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 12,
                            Address = "Northwest",
                            InternalCode = "SMTP",
                            Name = "Jamarcus Ernser",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 13,
                            Address = "Southwest",
                            InternalCode = "SSL",
                            Name = "Marjorie Funk",
                            OwnerId = 5,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 14,
                            Address = "North",
                            InternalCode = "TCP",
                            Name = "Efren Upton",
                            OwnerId = 3,
                            Price = 2017m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 15,
                            Address = "East",
                            InternalCode = "COM",
                            Name = "Joany Boyer",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 16,
                            Address = "North",
                            InternalCode = "ADP",
                            Name = "Cassandre Klocko",
                            OwnerId = 6,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 17,
                            Address = "North",
                            InternalCode = "IB",
                            Name = "Guido Parisian",
                            OwnerId = 9,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 18,
                            Address = "South",
                            InternalCode = "COM",
                            Name = "Cathryn Hoppe",
                            OwnerId = 3,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 19,
                            Address = "Northeast",
                            InternalCode = "PCI",
                            Name = "Lucio MacGyver",
                            OwnerId = 7,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 20,
                            Address = "South",
                            InternalCode = "CSS",
                            Name = "Forest Cole",
                            OwnerId = 4,
                            Price = 2020m,
                            Year = 0
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.Property<int>("PropertyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            PropertyImageId = 1,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=657",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 2,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=886",
                            PropertyId = 15
                        },
                        new
                        {
                            PropertyImageId = 3,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=560",
                            PropertyId = 9
                        },
                        new
                        {
                            PropertyImageId = 4,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=1071",
                            PropertyId = 1
                        },
                        new
                        {
                            PropertyImageId = 5,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=188",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 6,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=541",
                            PropertyId = 1
                        },
                        new
                        {
                            PropertyImageId = 7,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=942",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 8,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=889",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 9,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=774",
                            PropertyId = 1
                        },
                        new
                        {
                            PropertyImageId = 10,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=873",
                            PropertyId = 17
                        },
                        new
                        {
                            PropertyImageId = 11,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=151",
                            PropertyId = 4
                        },
                        new
                        {
                            PropertyImageId = 12,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=564",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 13,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=1063",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 14,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=624",
                            PropertyId = 18
                        },
                        new
                        {
                            PropertyImageId = 15,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=370",
                            PropertyId = 18
                        },
                        new
                        {
                            PropertyImageId = 16,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=704",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 17,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=848",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 18,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=1052",
                            PropertyId = 6
                        },
                        new
                        {
                            PropertyImageId = 19,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=692",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 20,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=985",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 21,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=750",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 22,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=709",
                            PropertyId = 7
                        },
                        new
                        {
                            PropertyImageId = 23,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=959",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 24,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=759",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 25,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=805",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 26,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=717",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 27,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=355",
                            PropertyId = 17
                        },
                        new
                        {
                            PropertyImageId = 28,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=57",
                            PropertyId = 19
                        },
                        new
                        {
                            PropertyImageId = 29,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=539",
                            PropertyId = 15
                        },
                        new
                        {
                            PropertyImageId = 30,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=646",
                            PropertyId = 16
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.Property<int>("PropertyTraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyTraceId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyTraces");

                    b.HasData(
                        new
                        {
                            PropertyTraceId = 1,
                            Name = "Devan Islands",
                            PropertyId = 13,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4575126550428160m
                        },
                        new
                        {
                            PropertyTraceId = 2,
                            Name = "Cassin Green",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8301512663393060m
                        },
                        new
                        {
                            PropertyTraceId = 3,
                            Name = "Osinski Canyon",
                            PropertyId = 7,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2389421035716970m
                        },
                        new
                        {
                            PropertyTraceId = 4,
                            Name = "Gunnar Common",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.771089599826880m
                        },
                        new
                        {
                            PropertyTraceId = 5,
                            Name = "Ollie Lakes",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7829831702555450m
                        },
                        new
                        {
                            PropertyTraceId = 6,
                            Name = "Lubowitz Way",
                            PropertyId = 19,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4594430133977170m
                        },
                        new
                        {
                            PropertyTraceId = 7,
                            Name = "Kay Canyon",
                            PropertyId = 6,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.253583771294720m
                        },
                        new
                        {
                            PropertyTraceId = 8,
                            Name = "Friesen Ports",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.121412397884490m
                        },
                        new
                        {
                            PropertyTraceId = 9,
                            Name = "Schroeder Walk",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.432398107569850m
                        },
                        new
                        {
                            PropertyTraceId = 10,
                            Name = "Dietrich Walks",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7582780745617480m
                        },
                        new
                        {
                            PropertyTraceId = 11,
                            Name = "Strosin Isle",
                            PropertyId = 18,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.07134133254705990m
                        },
                        new
                        {
                            PropertyTraceId = 12,
                            Name = "Jones Run",
                            PropertyId = 15,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9226692933229120m
                        },
                        new
                        {
                            PropertyTraceId = 13,
                            Name = "Earnestine Meadows",
                            PropertyId = 7,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7239425888862190m
                        },
                        new
                        {
                            PropertyTraceId = 14,
                            Name = "Raphael Isle",
                            PropertyId = 18,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.876573886199190m
                        },
                        new
                        {
                            PropertyTraceId = 15,
                            Name = "Tania Knoll",
                            PropertyId = 2,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2184154746208410m
                        },
                        new
                        {
                            PropertyTraceId = 16,
                            Name = "Alize Summit",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.3975971869181830m
                        },
                        new
                        {
                            PropertyTraceId = 17,
                            Name = "Tiana Island",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5453073845921580m
                        },
                        new
                        {
                            PropertyTraceId = 18,
                            Name = "Magnolia Springs",
                            PropertyId = 2,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.03393443489164790m
                        },
                        new
                        {
                            PropertyTraceId = 19,
                            Name = "O'Kon Trail",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8487964569818210m
                        },
                        new
                        {
                            PropertyTraceId = 20,
                            Name = "Taurean Plaza",
                            PropertyId = 4,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6319951087385390m
                        },
                        new
                        {
                            PropertyTraceId = 21,
                            Name = "Cartwright Stravenue",
                            PropertyId = 14,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7031269100043580m
                        },
                        new
                        {
                            PropertyTraceId = 22,
                            Name = "Ward Brook",
                            PropertyId = 10,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.06568253229636820m
                        },
                        new
                        {
                            PropertyTraceId = 23,
                            Name = "Ava Dam",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.08518070033061350m
                        },
                        new
                        {
                            PropertyTraceId = 24,
                            Name = "Roob Ranch",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.861998723755590m
                        },
                        new
                        {
                            PropertyTraceId = 25,
                            Name = "Willa Cape",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9102720054380m
                        },
                        new
                        {
                            PropertyTraceId = 26,
                            Name = "Clementina Meadows",
                            PropertyId = 2,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7748858387465060m
                        },
                        new
                        {
                            PropertyTraceId = 27,
                            Name = "Koch Via",
                            PropertyId = 13,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4437518177757750m
                        },
                        new
                        {
                            PropertyTraceId = 28,
                            Name = "Lehner River",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.3593702862781330m
                        },
                        new
                        {
                            PropertyTraceId = 29,
                            Name = "Ole Knoll",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9586703148478040m
                        },
                        new
                        {
                            PropertyTraceId = 30,
                            Name = "Bryana Points",
                            PropertyId = 5,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.09067324227219130m
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.HasOne("MillionAndUp.Data.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyTraces")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Navigation("PropertyImages");

                    b.Navigation("PropertyTraces");
                });
#pragma warning restore 612, 618
        }
    }
}
