// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MillionAndUp.Data;

namespace MillionAndUp.Data.Migrations
{
    [DbContext(typeof(MillionUpDbContext))]
    [Migration("20210424234524_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Address = "Northwest",
                            Birthday = new DateTime(2019, 9, 3, 23, 54, 56, 931, DateTimeKind.Unspecified).AddTicks(1331),
                            Name = "Wilfredo Jacobi",
                            Photo = "https://picsum.photos/640/480/?image=186"
                        },
                        new
                        {
                            OwnerId = 2,
                            Address = "North",
                            Birthday = new DateTime(2020, 9, 2, 10, 27, 4, 311, DateTimeKind.Unspecified).AddTicks(7607),
                            Name = "Abdullah Kub",
                            Photo = "https://picsum.photos/640/480/?image=632"
                        },
                        new
                        {
                            OwnerId = 3,
                            Address = "North",
                            Birthday = new DateTime(2010, 9, 27, 5, 43, 14, 975, DateTimeKind.Unspecified).AddTicks(8450),
                            Name = "Kevin Smith",
                            Photo = "https://picsum.photos/640/480/?image=335"
                        },
                        new
                        {
                            OwnerId = 4,
                            Address = "West",
                            Birthday = new DateTime(2002, 11, 8, 4, 51, 8, 233, DateTimeKind.Unspecified).AddTicks(4424),
                            Name = "Alisa Fadel",
                            Photo = "https://picsum.photos/640/480/?image=786"
                        },
                        new
                        {
                            OwnerId = 5,
                            Address = "South",
                            Birthday = new DateTime(2020, 3, 17, 10, 20, 49, 374, DateTimeKind.Unspecified).AddTicks(784),
                            Name = "Merlin Rempel",
                            Photo = "https://picsum.photos/640/480/?image=185"
                        },
                        new
                        {
                            OwnerId = 6,
                            Address = "Southeast",
                            Birthday = new DateTime(2014, 6, 24, 22, 52, 41, 439, DateTimeKind.Unspecified).AddTicks(1686),
                            Name = "Okey Brakus",
                            Photo = "https://picsum.photos/640/480/?image=86"
                        },
                        new
                        {
                            OwnerId = 7,
                            Address = "West",
                            Birthday = new DateTime(1992, 10, 4, 9, 40, 20, 946, DateTimeKind.Unspecified).AddTicks(3776),
                            Name = "Jaime D'Amore",
                            Photo = "https://picsum.photos/640/480/?image=536"
                        },
                        new
                        {
                            OwnerId = 8,
                            Address = "East",
                            Birthday = new DateTime(2009, 7, 25, 21, 9, 16, 89, DateTimeKind.Unspecified).AddTicks(4858),
                            Name = "Barbara Quigley",
                            Photo = "https://picsum.photos/640/480/?image=290"
                        },
                        new
                        {
                            OwnerId = 9,
                            Address = "Southwest",
                            Birthday = new DateTime(2012, 5, 29, 6, 29, 34, 296, DateTimeKind.Unspecified).AddTicks(1332),
                            Name = "Vesta Doyle",
                            Photo = "https://picsum.photos/640/480/?image=50"
                        },
                        new
                        {
                            OwnerId = 10,
                            Address = "East",
                            Birthday = new DateTime(2010, 10, 10, 4, 49, 19, 106, DateTimeKind.Unspecified).AddTicks(1887),
                            Name = "Oliver Kling",
                            Photo = "https://picsum.photos/640/480/?image=908"
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "Southeast",
                            InternalCode = "CSS",
                            Name = "Anne Murazik",
                            OwnerId = 1,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "East",
                            InternalCode = "IB",
                            Name = "Julio Fritsch",
                            OwnerId = 3,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "Southwest",
                            InternalCode = "AI",
                            Name = "Maymie Graham",
                            OwnerId = 7,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 4,
                            Address = "Northeast",
                            InternalCode = "AI",
                            Name = "Orin Schuppe",
                            OwnerId = 8,
                            Price = 2017m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 5,
                            Address = "North",
                            InternalCode = "AGP",
                            Name = "Eve Thompson",
                            OwnerId = 4,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 6,
                            Address = "Northeast",
                            InternalCode = "JBOD",
                            Name = "Esmeralda Wilkinson",
                            OwnerId = 3,
                            Price = 2017m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 7,
                            Address = "Northwest",
                            InternalCode = "SQL",
                            Name = "Madilyn Lakin",
                            OwnerId = 6,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 8,
                            Address = "South",
                            InternalCode = "AGP",
                            Name = "Adrienne Gislason",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 9,
                            Address = "East",
                            InternalCode = "IB",
                            Name = "Sebastian Kling",
                            OwnerId = 2,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 10,
                            Address = "Southwest",
                            InternalCode = "SMS",
                            Name = "Garnet Hagenes",
                            OwnerId = 1,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 11,
                            Address = "Northeast",
                            InternalCode = "SCSI",
                            Name = "Schuyler Stamm",
                            OwnerId = 1,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 12,
                            Address = "West",
                            InternalCode = "SSL",
                            Name = "Jerad Lynch",
                            OwnerId = 3,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 13,
                            Address = "West",
                            InternalCode = "COM",
                            Name = "Emmalee Tromp",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 14,
                            Address = "North",
                            InternalCode = "RAM",
                            Name = "Neoma Wilderman",
                            OwnerId = 2,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 15,
                            Address = "Northeast",
                            InternalCode = "TCP",
                            Name = "Amelia Schulist",
                            OwnerId = 7,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 16,
                            Address = "Southeast",
                            InternalCode = "ADP",
                            Name = "Kenyon Weber",
                            OwnerId = 1,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 17,
                            Address = "Northeast",
                            InternalCode = "FTP",
                            Name = "Vivianne Nader",
                            OwnerId = 8,
                            Price = 2015m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 18,
                            Address = "North",
                            InternalCode = "TCP",
                            Name = "Maggie Reilly",
                            OwnerId = 2,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 19,
                            Address = "West",
                            InternalCode = "XML",
                            Name = "Will Howe",
                            OwnerId = 7,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 20,
                            Address = "West",
                            InternalCode = "SDD",
                            Name = "Gillian Quitzon",
                            OwnerId = 9,
                            Price = 2015m,
                            Year = 0
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.Property<int>("PropertyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            PropertyImageId = 1,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=86",
                            PropertyId = 6
                        },
                        new
                        {
                            PropertyImageId = 2,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=1055",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 3,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=903",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 4,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=559",
                            PropertyId = 7
                        },
                        new
                        {
                            PropertyImageId = 5,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=471",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 6,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=850",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 7,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=845",
                            PropertyId = 19
                        },
                        new
                        {
                            PropertyImageId = 8,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=144",
                            PropertyId = 7
                        },
                        new
                        {
                            PropertyImageId = 9,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=2",
                            PropertyId = 17
                        },
                        new
                        {
                            PropertyImageId = 10,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=973",
                            PropertyId = 12
                        },
                        new
                        {
                            PropertyImageId = 11,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=31",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 12,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=614",
                            PropertyId = 1
                        },
                        new
                        {
                            PropertyImageId = 13,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=950",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 14,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=642",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 15,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=622",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 16,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=785",
                            PropertyId = 4
                        },
                        new
                        {
                            PropertyImageId = 17,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=345",
                            PropertyId = 19
                        },
                        new
                        {
                            PropertyImageId = 18,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=1021",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 19,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=1043",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 20,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=656",
                            PropertyId = 9
                        },
                        new
                        {
                            PropertyImageId = 21,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=127",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 22,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=964",
                            PropertyId = 14
                        },
                        new
                        {
                            PropertyImageId = 23,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=1020",
                            PropertyId = 13
                        },
                        new
                        {
                            PropertyImageId = 24,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=275",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 25,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=273",
                            PropertyId = 13
                        },
                        new
                        {
                            PropertyImageId = 26,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=523",
                            PropertyId = 4
                        },
                        new
                        {
                            PropertyImageId = 27,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=881",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 28,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=75",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 29,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=964",
                            PropertyId = 17
                        },
                        new
                        {
                            PropertyImageId = 30,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=260",
                            PropertyId = 11
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.Property<int>("PropertyTraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyTraceId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyTraces");

                    b.HasData(
                        new
                        {
                            PropertyTraceId = 1,
                            Name = "Camren Inlet",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8988235825201610m
                        },
                        new
                        {
                            PropertyTraceId = 2,
                            Name = "Imani Forest",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.3484679485431260m
                        },
                        new
                        {
                            PropertyTraceId = 3,
                            Name = "Aufderhar Walks",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2737654271879070m
                        },
                        new
                        {
                            PropertyTraceId = 4,
                            Name = "Osinski Run",
                            PropertyId = 18,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4251190244337170m
                        },
                        new
                        {
                            PropertyTraceId = 5,
                            Name = "Vaughn Ports",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4147829662145970m
                        },
                        new
                        {
                            PropertyTraceId = 6,
                            Name = "Jennyfer Courts",
                            PropertyId = 6,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.1334006726431660m
                        },
                        new
                        {
                            PropertyTraceId = 7,
                            Name = "Jaime Mountain",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6836994293535590m
                        },
                        new
                        {
                            PropertyTraceId = 8,
                            Name = "Virginia Flat",
                            PropertyId = 17,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5829359495932870m
                        },
                        new
                        {
                            PropertyTraceId = 9,
                            Name = "Cecil Circles",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9662579898565350m
                        },
                        new
                        {
                            PropertyTraceId = 10,
                            Name = "Yessenia Glens",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.498256134566970m
                        },
                        new
                        {
                            PropertyTraceId = 11,
                            Name = "Susana Divide",
                            PropertyId = 7,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2321868833304320m
                        },
                        new
                        {
                            PropertyTraceId = 12,
                            Name = "Cordia Run",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.1406202228463350m
                        },
                        new
                        {
                            PropertyTraceId = 13,
                            Name = "Nolan Skyway",
                            PropertyId = 4,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9363964483777040m
                        },
                        new
                        {
                            PropertyTraceId = 14,
                            Name = "Shanahan Glens",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6597609592879940m
                        },
                        new
                        {
                            PropertyTraceId = 15,
                            Name = "Crystel Summit",
                            PropertyId = 7,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8618038626675510m
                        },
                        new
                        {
                            PropertyTraceId = 16,
                            Name = "Macejkovic Ways",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9723520139103530m
                        },
                        new
                        {
                            PropertyTraceId = 17,
                            Name = "Huels Spurs",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.3514273126383440m
                        },
                        new
                        {
                            PropertyTraceId = 18,
                            Name = "Ryan Drive",
                            PropertyId = 14,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2253396605259460m
                        },
                        new
                        {
                            PropertyTraceId = 19,
                            Name = "Crist Extensions",
                            PropertyId = 15,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2383566863082150m
                        },
                        new
                        {
                            PropertyTraceId = 20,
                            Name = "Shanelle Radial",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8447819798462010m
                        },
                        new
                        {
                            PropertyTraceId = 21,
                            Name = "Howell Square",
                            PropertyId = 6,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7160553902928040m
                        },
                        new
                        {
                            PropertyTraceId = 22,
                            Name = "Edna Terrace",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.662885856192040m
                        },
                        new
                        {
                            PropertyTraceId = 23,
                            Name = "Jerde Via",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.03921903764792670m
                        },
                        new
                        {
                            PropertyTraceId = 24,
                            Name = "Hilda Passage",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.658288118270360m
                        },
                        new
                        {
                            PropertyTraceId = 25,
                            Name = "Dicki Lights",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.07049619456310580m
                        },
                        new
                        {
                            PropertyTraceId = 26,
                            Name = "Gillian Mountains",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.1187358405993950m
                        },
                        new
                        {
                            PropertyTraceId = 27,
                            Name = "Kadin Garden",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5711676229588540m
                        },
                        new
                        {
                            PropertyTraceId = 28,
                            Name = "Becker Highway",
                            PropertyId = 19,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.1584835244149360m
                        },
                        new
                        {
                            PropertyTraceId = 29,
                            Name = "Abbott Crossing",
                            PropertyId = 14,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5262238055124060m
                        },
                        new
                        {
                            PropertyTraceId = 30,
                            Name = "Goldner Spring",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5091924469495160m
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.HasOne("MillionAndUp.Data.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyTraces")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Navigation("PropertyImages");

                    b.Navigation("PropertyTraces");
                });
#pragma warning restore 612, 618
        }
    }
}
