// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MillionAndUp.Data;

namespace MillionAndUp.Data.Migrations
{
    [DbContext(typeof(MillionUpDbContext))]
    [Migration("20210425000240_SeedUsers")]
    partial class SeedUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Address = "East",
                            Birthday = new DateTime(1994, 12, 5, 18, 4, 7, 906, DateTimeKind.Unspecified).AddTicks(3813),
                            Name = "Afton Heathcote",
                            Photo = "https://picsum.photos/640/480/?image=524"
                        },
                        new
                        {
                            OwnerId = 2,
                            Address = "East",
                            Birthday = new DateTime(2012, 5, 16, 15, 3, 48, 524, DateTimeKind.Unspecified).AddTicks(162),
                            Name = "Shad Shields",
                            Photo = "https://picsum.photos/640/480/?image=413"
                        },
                        new
                        {
                            OwnerId = 3,
                            Address = "West",
                            Birthday = new DateTime(1995, 4, 2, 1, 31, 34, 125, DateTimeKind.Unspecified).AddTicks(8586),
                            Name = "Adan Lowe",
                            Photo = "https://picsum.photos/640/480/?image=554"
                        },
                        new
                        {
                            OwnerId = 4,
                            Address = "Northeast",
                            Birthday = new DateTime(2008, 5, 28, 0, 40, 10, 47, DateTimeKind.Unspecified).AddTicks(1958),
                            Name = "Constance Hahn",
                            Photo = "https://picsum.photos/640/480/?image=672"
                        },
                        new
                        {
                            OwnerId = 5,
                            Address = "North",
                            Birthday = new DateTime(2013, 5, 23, 20, 22, 6, 404, DateTimeKind.Unspecified).AddTicks(1992),
                            Name = "Alaina Rice",
                            Photo = "https://picsum.photos/640/480/?image=614"
                        },
                        new
                        {
                            OwnerId = 6,
                            Address = "Northwest",
                            Birthday = new DateTime(2002, 1, 28, 9, 30, 41, 684, DateTimeKind.Unspecified).AddTicks(3425),
                            Name = "Foster O'Reilly",
                            Photo = "https://picsum.photos/640/480/?image=6"
                        },
                        new
                        {
                            OwnerId = 7,
                            Address = "Southwest",
                            Birthday = new DateTime(2011, 10, 23, 8, 46, 38, 176, DateTimeKind.Unspecified).AddTicks(1323),
                            Name = "Lester Koepp",
                            Photo = "https://picsum.photos/640/480/?image=311"
                        },
                        new
                        {
                            OwnerId = 8,
                            Address = "West",
                            Birthday = new DateTime(1996, 6, 23, 1, 38, 43, 674, DateTimeKind.Unspecified).AddTicks(3852),
                            Name = "Ricardo Smith",
                            Photo = "https://picsum.photos/640/480/?image=173"
                        },
                        new
                        {
                            OwnerId = 9,
                            Address = "Southwest",
                            Birthday = new DateTime(2002, 8, 5, 9, 49, 2, 736, DateTimeKind.Unspecified).AddTicks(9594),
                            Name = "Richie Kunze",
                            Photo = "https://picsum.photos/640/480/?image=511"
                        },
                        new
                        {
                            OwnerId = 10,
                            Address = "East",
                            Birthday = new DateTime(2015, 4, 24, 10, 40, 2, 292, DateTimeKind.Unspecified).AddTicks(8929),
                            Name = "Aubree Bashirian",
                            Photo = "https://picsum.photos/640/480/?image=178"
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "North",
                            InternalCode = "USB",
                            Name = "Elenora Parker",
                            OwnerId = 2,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "Southeast",
                            InternalCode = "RSS",
                            Name = "Willis Grady",
                            OwnerId = 5,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "East",
                            InternalCode = "SAS",
                            Name = "Willard Leannon",
                            OwnerId = 9,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 4,
                            Address = "Northwest",
                            InternalCode = "EXE",
                            Name = "Malika Mayer",
                            OwnerId = 1,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 5,
                            Address = "North",
                            InternalCode = "HTTP",
                            Name = "Devonte Nader",
                            OwnerId = 6,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 6,
                            Address = "East",
                            InternalCode = "PNG",
                            Name = "Frieda Corwin",
                            OwnerId = 8,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 7,
                            Address = "South",
                            InternalCode = "COM",
                            Name = "Lawson Leffler",
                            OwnerId = 4,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 8,
                            Address = "South",
                            InternalCode = "XML",
                            Name = "Gregory D'Amore",
                            OwnerId = 7,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 9,
                            Address = "South",
                            InternalCode = "XSS",
                            Name = "Peter Larson",
                            OwnerId = 8,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 10,
                            Address = "Southwest",
                            InternalCode = "HTTP",
                            Name = "Francesca Lehner",
                            OwnerId = 4,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 11,
                            Address = "East",
                            InternalCode = "XSS",
                            Name = "Americo Hodkiewicz",
                            OwnerId = 4,
                            Price = 2018m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 12,
                            Address = "Southeast",
                            InternalCode = "SCSI",
                            Name = "Leta Adams",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 13,
                            Address = "Southeast",
                            InternalCode = "AI",
                            Name = "Elza Blick",
                            OwnerId = 8,
                            Price = 2019m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 14,
                            Address = "Southeast",
                            InternalCode = "GB",
                            Name = "Amira Dach",
                            OwnerId = 7,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 15,
                            Address = "East",
                            InternalCode = "RSS",
                            Name = "Joyce Hamill",
                            OwnerId = 2,
                            Price = 2020m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 16,
                            Address = "North",
                            InternalCode = "SAS",
                            Name = "Aileen Durgan",
                            OwnerId = 6,
                            Price = 2017m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 17,
                            Address = "North",
                            InternalCode = "GB",
                            Name = "Cleta Rath",
                            OwnerId = 8,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 18,
                            Address = "East",
                            InternalCode = "USB",
                            Name = "Darien Rohan",
                            OwnerId = 9,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 19,
                            Address = "Southwest",
                            InternalCode = "JBOD",
                            Name = "Myles Blanda",
                            OwnerId = 6,
                            Price = 2016m,
                            Year = 0
                        },
                        new
                        {
                            PropertyId = 20,
                            Address = "East",
                            InternalCode = "HDD",
                            Name = "Wava Emmerich",
                            OwnerId = 5,
                            Price = 2018m,
                            Year = 0
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.Property<int>("PropertyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            PropertyImageId = 1,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=750",
                            PropertyId = 9
                        },
                        new
                        {
                            PropertyImageId = 2,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=277",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 3,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=373",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 4,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=485",
                            PropertyId = 4
                        },
                        new
                        {
                            PropertyImageId = 5,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=744",
                            PropertyId = 12
                        },
                        new
                        {
                            PropertyImageId = 6,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=445",
                            PropertyId = 6
                        },
                        new
                        {
                            PropertyImageId = 7,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=405",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 8,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=17",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 9,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=349",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 10,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=810",
                            PropertyId = 14
                        },
                        new
                        {
                            PropertyImageId = 11,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=1065",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 12,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=721",
                            PropertyId = 12
                        },
                        new
                        {
                            PropertyImageId = 13,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=968",
                            PropertyId = 5
                        },
                        new
                        {
                            PropertyImageId = 14,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=725",
                            PropertyId = 12
                        },
                        new
                        {
                            PropertyImageId = 15,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=198",
                            PropertyId = 1
                        },
                        new
                        {
                            PropertyImageId = 16,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=185",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 17,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=165",
                            PropertyId = 8
                        },
                        new
                        {
                            PropertyImageId = 18,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=830",
                            PropertyId = 4
                        },
                        new
                        {
                            PropertyImageId = 19,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=1032",
                            PropertyId = 13
                        },
                        new
                        {
                            PropertyImageId = 20,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=503",
                            PropertyId = 2
                        },
                        new
                        {
                            PropertyImageId = 21,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=287",
                            PropertyId = 17
                        },
                        new
                        {
                            PropertyImageId = 22,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=500",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 23,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=368",
                            PropertyId = 11
                        },
                        new
                        {
                            PropertyImageId = 24,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=388",
                            PropertyId = 14
                        },
                        new
                        {
                            PropertyImageId = 25,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=64",
                            PropertyId = 19
                        },
                        new
                        {
                            PropertyImageId = 26,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=726",
                            PropertyId = 10
                        },
                        new
                        {
                            PropertyImageId = 27,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=509",
                            PropertyId = 16
                        },
                        new
                        {
                            PropertyImageId = 28,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=662",
                            PropertyId = 3
                        },
                        new
                        {
                            PropertyImageId = 29,
                            Enabled = false,
                            FilePath = "https://picsum.photos/640/480/?image=761",
                            PropertyId = 18
                        },
                        new
                        {
                            PropertyImageId = 30,
                            Enabled = true,
                            FilePath = "https://picsum.photos/640/480/?image=467",
                            PropertyId = 9
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.Property<int>("PropertyTraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyTraceId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyTraces");

                    b.HasData(
                        new
                        {
                            PropertyTraceId = 1,
                            Name = "Janae Loaf",
                            PropertyId = 19,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8462872979446720m
                        },
                        new
                        {
                            PropertyTraceId = 2,
                            Name = "Beaulah Tunnel",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8091080397409890m
                        },
                        new
                        {
                            PropertyTraceId = 3,
                            Name = "Hettinger Turnpike",
                            PropertyId = 6,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5888469776086730m
                        },
                        new
                        {
                            PropertyTraceId = 4,
                            Name = "Kovacek Points",
                            PropertyId = 17,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.581725420701190m
                        },
                        new
                        {
                            PropertyTraceId = 5,
                            Name = "Lorena Flat",
                            PropertyId = 16,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7511175264376760m
                        },
                        new
                        {
                            PropertyTraceId = 6,
                            Name = "Hills Valley",
                            PropertyId = 1,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.04110817985660780m
                        },
                        new
                        {
                            PropertyTraceId = 7,
                            Name = "Keshaun Street",
                            PropertyId = 5,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8892261525100220m
                        },
                        new
                        {
                            PropertyTraceId = 8,
                            Name = "Rosenbaum Village",
                            PropertyId = 13,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2592070448488030m
                        },
                        new
                        {
                            PropertyTraceId = 9,
                            Name = "Curtis Burg",
                            PropertyId = 14,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7963800364157090m
                        },
                        new
                        {
                            PropertyTraceId = 10,
                            Name = "Morar Alley",
                            PropertyId = 11,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2356751990670690m
                        },
                        new
                        {
                            PropertyTraceId = 11,
                            Name = "Katelynn Plaza",
                            PropertyId = 13,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6964086562844040m
                        },
                        new
                        {
                            PropertyTraceId = 12,
                            Name = "Armand Ridge",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9991365442979780m
                        },
                        new
                        {
                            PropertyTraceId = 13,
                            Name = "Barrows Spurs",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.06824146866250850m
                        },
                        new
                        {
                            PropertyTraceId = 14,
                            Name = "Marietta Mission",
                            PropertyId = 9,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.8802099259943750m
                        },
                        new
                        {
                            PropertyTraceId = 15,
                            Name = "Jacobs Ranch",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4600264660362280m
                        },
                        new
                        {
                            PropertyTraceId = 16,
                            Name = "Abbey Terrace",
                            PropertyId = 19,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9139938712650880m
                        },
                        new
                        {
                            PropertyTraceId = 17,
                            Name = "Lorenz Glen",
                            PropertyId = 3,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6901753208088570m
                        },
                        new
                        {
                            PropertyTraceId = 18,
                            Name = "Romaine Plaza",
                            PropertyId = 6,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6080328284800210m
                        },
                        new
                        {
                            PropertyTraceId = 19,
                            Name = "Yundt Mill",
                            PropertyId = 5,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.1904735556759280m
                        },
                        new
                        {
                            PropertyTraceId = 20,
                            Name = "Fadel Square",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.08989608012600620m
                        },
                        new
                        {
                            PropertyTraceId = 21,
                            Name = "Smitham Fort",
                            PropertyId = 18,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.9252294520499320m
                        },
                        new
                        {
                            PropertyTraceId = 22,
                            Name = "Tillman Square",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6223258146188810m
                        },
                        new
                        {
                            PropertyTraceId = 23,
                            Name = "Corkery Forge",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5558681481312350m
                        },
                        new
                        {
                            PropertyTraceId = 24,
                            Name = "Littel Walk",
                            PropertyId = 8,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.2505453029882840m
                        },
                        new
                        {
                            PropertyTraceId = 25,
                            Name = "Rath Gateway",
                            PropertyId = 14,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.6145707041093010m
                        },
                        new
                        {
                            PropertyTraceId = 26,
                            Name = "Abshire Overpass",
                            PropertyId = 12,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.7852373923106290m
                        },
                        new
                        {
                            PropertyTraceId = 27,
                            Name = "Charlene Lights",
                            PropertyId = 17,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.4812139009503710m
                        },
                        new
                        {
                            PropertyTraceId = 28,
                            Name = "Emile Crest",
                            PropertyId = 13,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.3281813153662630m
                        },
                        new
                        {
                            PropertyTraceId = 29,
                            Name = "McGlynn Path",
                            PropertyId = 5,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.428296189023320m
                        },
                        new
                        {
                            PropertyTraceId = 30,
                            Name = "Ward Views",
                            PropertyId = 2,
                            SaleDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tax = 0m,
                            Value = 0.5298357082204130m
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "Rosalia",
                            LastName = "O'Reilly",
                            Password = "_7Oy0rMQkJ",
                            Username = "Will.Gulgowski"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Elsa",
                            LastName = "Kihn",
                            Password = "zSPhigi82P",
                            Username = "Gladyce_Altenwerth35"
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "Fannie",
                            LastName = "Koepp",
                            Password = "Hd8FR5WMee",
                            Username = "Tomasa39"
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "Destini",
                            LastName = "Denesik",
                            Password = "1pPVvRP6E7",
                            Username = "Gwen.Cummings28"
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "Filomena",
                            LastName = "Murray",
                            Password = "P4242p3s5p",
                            Username = "Marcia.Feil97"
                        },
                        new
                        {
                            UserId = 6,
                            FirstName = "Winona",
                            LastName = "Pfeffer",
                            Password = "Y7uMCP08Fi",
                            Username = "Merl.Armstrong"
                        },
                        new
                        {
                            UserId = 7,
                            FirstName = "Walker",
                            LastName = "Boyle",
                            Password = "NyB9jaS2GX",
                            Username = "Shayne48"
                        },
                        new
                        {
                            UserId = 8,
                            FirstName = "Franz",
                            LastName = "Mohr",
                            Password = "4apqL28gnE",
                            Username = "Tristian_Halvorson70"
                        },
                        new
                        {
                            UserId = 9,
                            FirstName = "Justina",
                            LastName = "Hammes",
                            Password = "m37pnKFBVY",
                            Username = "Rhea53"
                        },
                        new
                        {
                            UserId = 10,
                            FirstName = "Oral",
                            LastName = "Spinka",
                            Password = "2sWdlt9RNj",
                            Username = "Lois89"
                        },
                        new
                        {
                            UserId = 11,
                            FirstName = "Ashton",
                            LastName = "Lakin",
                            Password = "MjtXRrjgM2",
                            Username = "Jaime.Hilpert79"
                        },
                        new
                        {
                            UserId = 12,
                            FirstName = "Jarrod",
                            LastName = "Feest",
                            Password = "m7u91rrRjr",
                            Username = "Ludie37"
                        },
                        new
                        {
                            UserId = 13,
                            FirstName = "Aylin",
                            LastName = "Haley",
                            Password = "GVIqkELDTZ",
                            Username = "Janet.Runolfsson"
                        },
                        new
                        {
                            UserId = 14,
                            FirstName = "Enrique",
                            LastName = "Lesch",
                            Password = "faIIz6nDC2",
                            Username = "Gertrude.Kiehn6"
                        },
                        new
                        {
                            UserId = 15,
                            FirstName = "Amara",
                            LastName = "Funk",
                            Password = "Fc5vfCCqbj",
                            Username = "Vicenta_Howell"
                        },
                        new
                        {
                            UserId = 16,
                            FirstName = "Syble",
                            LastName = "Wiegand",
                            Password = "b0HHD0xX43",
                            Username = "Ines_Ullrich"
                        },
                        new
                        {
                            UserId = 17,
                            FirstName = "Cordia",
                            LastName = "Veum",
                            Password = "1x9YuafQed",
                            Username = "Jace88"
                        },
                        new
                        {
                            UserId = 18,
                            FirstName = "Randy",
                            LastName = "Koepp",
                            Password = "49Ma6bP0SA",
                            Username = "Laurine_Block44"
                        },
                        new
                        {
                            UserId = 19,
                            FirstName = "Casandra",
                            LastName = "Kirlin",
                            Password = "ZmaBUfZoKT",
                            Username = "Nick34"
                        });
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.HasOne("MillionAndUp.Data.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyImage", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.PropertyTrace", b =>
                {
                    b.HasOne("MillionAndUp.Data.Property", "Property")
                        .WithMany("PropertyTraces")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MillionAndUp.Data.Owner", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MillionAndUp.Data.Property", b =>
                {
                    b.Navigation("PropertyImages");

                    b.Navigation("PropertyTraces");
                });
#pragma warning restore 612, 618
        }
    }
}
